name: CI/CD Pipeline - PySpark ETL - AWS S3

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code_quality_tests:
    name: Code Quality and Tests (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t pyspark-etl-app:latest .

      - name: Run Flake8 Linting in Container
        run: |
          docker run --rm pyspark-etl-app:latest flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run PyTest in Container
        run: |
          docker run --rm pyspark-etl-app:latest pytest tests/ --doctest-modules -v

  deploy_to_s3_airflow:
    name: Deploy DAGs and Scripts to AWS S3
    needs: code_quality_tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync DAG and Spark Scripts to AWS S3
        run: |
          aws s3 sync ./dags s3://etlprodtest/airflow/dags/ --delete
          aws s3 sync ./scripts_spark s3://etlprodtest/airflow/scripts_spark/ --delete
